### ISSUE TITLE
Annoying error message says 'semicolon' when it means 'colon'

### ISSUE THREAD

**Issue by neil-greenwood** [josa42/atom-linter-json-lint#37]
I've just made a PR, codenothing/jsonlint#8, against the jsonlint repo, to fix the error message. The ':' character is a colon not a semicolon.

This code should be updated to get the new version when the PR is merged.

**Comment by neil-greenwood** [comment]
Why was this closed?

**Comment by josa42** [comment]
It's not an issue with this package and needs to be fixed in in `jsonlint`. Which did not happen `¯\_(ツ)_/¯`
